### ISSUE TITLE
Regression in ruby 3.2-rc: vendor/ruby/3.2.0+2/gems/liquid-4.0.3/lib/liquid/variable.rb:124:in `taint_check': undefined method `tainted?' for "Access Token":String (NoMethodError)

### ISSUE THREAD

**Issue by HoneyryderChuck** [Shopify/liquid#1625]
While updating some CI builds using jekyll to use `ruby:3.2-rc` docker image, I caught this error:

```
/vendor/ruby/3.2.0+2/gems/liquid-4.0.3/lib/liquid/variable.rb:124:in `taint_check': undefined method `tainted?' for "Access Token":String (NoMethodError)
      return unless obj.tainted?
                       ^^^^^^^^^
	from /vendor/ruby/3.2.0+2/gems/liquid-4.0.3/lib/liquid/variable.rb:89:in `render'
	from /vendor/ruby/3.2.0+2/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /vendor/ruby/3.2.0+2/gems/liquid-4.0.3/lib/liquid/block_body.rb:80:in `render'
	from /vendor/ruby/3.2.0+2/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	from /vendor/ruby/3.2.0+2/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	from /vendor/ruby/3.2.0+2/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	from /vendor/ruby/3.2.0+2/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	from /vendor/ruby/3.2.0+2/gems/jekyll-4.2.2/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
```

I think the method is to be removeed in ruby 3.2 .

**Comment by dylanahsmith** [comment]
This was fixed in #1268 and released in version 5.0.0 (https://github.com/Shopify/liquid/blob/master/History.md#500--2021-01-06)
