### PR TITLE
Fix exception from using an empty string for the table row collection.

### PR DESCRIPTION
**Pull request by dylanahsmith**
@fw42 & @tjoyal for review

## Problem

Liquid like `{% tablerow product in collections.frontpage.products cols:3  %}` was resulting in a `Liquid error: undefined method `each' for \"\":String` error when the shop doesn't have a frontpage collection.  This empty string was coming from an EmptyDrop that we returned when a collection couldn't be found.

This was inconsistent with the `for` tag, which would treat an empty string as an empty collection.  Both the `for` and `tablerow` tags will treat a non-empty string as a collection with a single item.  It is also inconsistent with how liquid worked with ruby 1.8.7, where String#each was the same as String#each_line.

## Solution

Treat an empty string the same as an empty collection.

### CODE REVIEW

File: lib/liquid/utils.rb [hunk 1]
```diff
@@ -17,7 +17,7 @@ def self.slice_collection_using_each(collection, from, to)
       index = 0
 
       # Maintains Ruby 1.8.7 String#each behaviour on 1.9
```
Comment (fw42) [inline lib/liquid/utils.rb]: does this comment still make sense now?

**Comment by fw42** [comment]
any backwards-compatibility concerns here?

File: lib/liquid/utils.rb [hunk 2]
```diff
@@ -17,7 +17,7 @@ def self.slice_collection_using_each(collection, from, to)
...
-      return [collection] if non_blank_string?(collection)
+      return collection != ''.freeze ? [collection] : [] if collection.is_a?(String)
```
Comment (fw42) [inline lib/liquid/utils.rb]: I find this line hard to read (the combination of a `if` suffix and a ternary). Can you make this a bit more explicit?

Maybe
```ruby
if collection.is_a?(String)
  return collection != ''.freeze ? [collection] : []
end
```

**Comment by fw42** [comment]
:+1:

File: lib/liquid/utils.rb (hunk 2 above)
Comment (parkr) [inline lib/liquid/utils.rb]: is `collection != ''.freeze` faster than `!collection.empty?`

File: lib/liquid/utils.rb (hunk 1 above)
Comment (dylanahsmith) [inline lib/liquid/utils.rb]: yes, this is still for backwards compatibility

File: lib/liquid/utils.rb (hunk 2 above)
Comment (dylanahsmith) [inline lib/liquid/utils.rb]: `!collection.empty?` is faster and more readable, so I changed this to

```ruby
      if collection.is_a?(String)
        return collection.empty? ? [] : [collection]
      end
```

**Comment by dylanahsmith** [comment]
> any backwards-compatibility concerns here?

No, because the code this affects is currently outputting a liquid error.

**Comment by tjoyal** [comment]
I think your changes will need to be reconsolidated with 
https://github.com/Shopify/liquid/blob/table-row-blank-string-collection/lib/liquid/tags/for.rb#L194

Should `for.rb#L194` be this?
`collection.respond_to?(:each) || collection.is_a?(String)`

I think this can be done safely, but you would need to re-validate.

**Comment by dylanahsmith** [comment]
> Should `for.rb#L194` be this?
> `collection.respond_to?(:each) || collection.is_a?(String)`

Actually, I think the `collection.is_a?(String)` check is also redundant.  We could probably also move the `collection.respond_to?(:each)` check into `Utils.slice_collection` for consistency, and to avoid another potential error from some other non-iterable being used.

**Comment by tjoyal** [comment]
:+1:
