### ISSUE TITLE
undefined method `line_number' in Liquid v5.0.1

### ISSUE THREAD

**Issue by oliwoodsuk** [Shopify/liquid#1420]
I updated a couple of Rails gems this morning due to the Mime magic stuff, including Liquid 4.0.3 to 5.0.1.
Straight away I started getting the below error in all of my custom mailers:
`ActionView::Template::Error (undefined method line_number' for "<p>Hi ":ActiveSupport::SafeBuffer):`
I reverted back to v4.0.3 as soon as I spotted it. 
This is roughly the setup that stops working in 5.0.1:

`#mailer.rb`
`@content = Liquid::Template.parse(simple_format(@shop.custom_content))`

`#email.html.erb`
`<%= render 'email_content', content: @content %>`

`#_email_content.html.erb`
`<%= 
	content.render(
		'product_name' => product_title,
		'variant_name' => variant_name,
		'customer_name' => customer_name, 
	).html_safe 
%>`

I ran a 'find all' in my project for 'line_number' but couldn't see anything. 'line_number' makes me think of line items, which would hint at a Shopify API kind of thing, but if that was it, down-grading Liquid wouldn't have fixed the issue like it did.

Any ideas what's going on?

Thanks,

Oli

**Comment by dylanahsmith** [comment]
Looks like this might be related to https://github.com/Shopify/liquid/issues/1390.

Liquid does call `line_number` internally.  Please include the relevant parts of the full backtrace when reporting an exception coming from liquid code, so we know where the exception is coming from

**Comment by dylanahsmith** [comment]
Oh, that issue was closed, but the corresponding pull request (https://github.com/Shopify/liquid/pull/1400) wasn't actually merged

**Comment by oliwoodsuk** [comment]
Ah, thanks for looking into this Dylan.
...and noted, next time I'll include it for sure.
