### ISSUE TITLE
NoMethodError: undefined method `reset' for {}:Hash

### ISSUE THREAD

**Issue by JulienItard** [Shopify/liquid#1083]
Hello, i updated my old liquid 2 to liquid 4 and now it raises me this error:

`NoMethodError: undefined method `reset' for {}:Hash`

The error come from `render` method: `liquid-4.0.3/lib/liquid/template.rb: 202:in render'`
Any idea ? Thanks a lot :) 

I use rails 4.2

**Comment by forsbergplustwo** [comment]
I'm getting the same issue when upgrading from Liquid 3.0.5 to 4.0.3:

Seems it's the following lines of the render method in lib/liquid/template.rb

```
      # Retrying a render resets resource usage
      context.resource_limits.reset
```

https://github.com/Shopify/liquid/blob/b0629f17f79a96eb7001b55ea0877b14b53b67a0/lib/liquid/template.rb#L201-L202

Unfortunately I don't know the internal of Liquid well enough to know why this is happening.

@JulienItard Did you get this worked out yourself?

**Comment by forsbergplustwo** [comment]
Edit: I worked this out, previously the render method could be called like this:

.render( assigns_hash, { filters: [MoneyFilter], registers: {} } )

now you call it without the hash of options:

.render( assigns_hash, filters: [MoneyFilter], registers: {} )

**Comment by shopmike** [comment]
I haven't been able to replicate how this has been triggered. Both `Template` and `Context` are designed to create `ResouceLimits` which will respond to reset. 

I'm closing this for now but if someone can provide more information, happy to investigate further.
